export const timeline = [
  {
    company: "PT. Pertamina Hulu Rokan",
    title: "Dataiku Development",
    date: "Aug 25 - Present",
    description: "Building a platform to help people manage their data",
    responsibilities: [
      "Developed a new feature that improves the user experience",
      "Implemented a recommendation algorithm to suggest the best data management practices",
      "Enhanced the platform's performance to handle large datasets",
      "Built a feature for tracking user activity",
    ],
  },
  {
    company: "PT. Indotech Berkah Abadi",
    title: "Back End Developer",
    date: "Sep 24 - Jan 25",
    description: "Building a platform to help people manage their finances",
    responsibilities: [
      "Developed a new feature that improves the user experience",
      "Implemented a recommendation algorithm to suggest the best financial products",
      "Enhanced the news feed algorithm to show more relevant posts",
      "Built a feature for tracking user activity",
    ],
  },
  {
    company: "Junior Web Developer ",
    title: "Digital Talent Scholarship",
    date: "Aug 2024 - Aug 2024",
    description: "Building a platform to help people find the best place to holiday",
    responsibilities: [
      "Developed a new feature that improves the user experience",
      "Implemented a recommendation algorithm to suggest the best place to holiday",
      "Enhanced the news feed algorithm to show more relevant posts",
      "Built a feature for tracking user activity",
    ],
  },
  {
    company: "Bangkit Academy 2024 By Google, GoTo, Traveloka - Cloud Computing Learning Path ",
    title: "Cloud Computing Learning Path",
    date: "Feb 2024 - June 2024",
    description: "Building BatikLens - A platform to help people to find the best Batik",
    responsibilities: [
      "Developed a new feature that improves the user experience",
      "Implemented a recommendation algorithm to suggest the best Batik",
      "Enhanced the news feed algorithm to show more relevant posts",
      "Built a feature for tracking user activity",
    ],
  },
  {
    company: "PT Solutionlabs Group Indonesia",
    title: "Front End Developer",
    date: "Des 2023 - Jan 2024",
    description: "Building the future of E-Learning",
    responsibilities: [
      "Improved the E-Learning platform to enhance user experience",
      "Developed a new feature that personalizes the learning experience",
      "Enhanced the platform to improve engagement",
      "Implemented a feature for tracking user progress",
    ],
  },
  {
    company: "Staff of Communication and Information Media Department",
    title: "Video Editor",
    date: "May 2023 - May 2024",
    description: "Building video content for the department",
    responsibilities: [
      "Improved the video editing process to enhance the quality of the videos",
      "Developed a new feature that personalizes video content",
      "Enhanced the video content to improve engagement",
      "Implemented a feature for tracking video performance",
    ],
  },
  {
    company: "B-Otomotif",
    title: "Full Stack Developer and Video Editor",
    date: "2018 - Present",
    description: "Building the future of automotive industry",
    responsibilities: [
      "Improved the platform to enhance user experience",
      "Developed a new feature that personalizes the user experience",
      "Enhanced the platform to improve engagement",
      "Implemented a feature for tracking user activity",
    ],
  },
];
